# .github/workflows/test-devops.yml
name: DevOps Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Hello, GitHub Actions!"
